### ISSUE TITLE
LDAP groups

### ISSUE THREAD

**Issue by wastez** [operasoftware/ssh-key-authority#55] opened 2021-10-21 07:58 UTC
Hello,

Thank you for this tool, it is great.
I've one question.
Would it be possible to manage groups over the ldap (not only the admin group)? 
This would be better to manage.

**Comment by thomas-pike** [comment] 2021-10-31 17:50
The `sync_groups` branch has an experimental implementation of this. Try it out with `git pull` and `git checkout sync_groups`. Configure the groups you want to sync by adding multiple lines like the following to the `[ldap]` section of the config:
```
sync_groups[] = name_of_first_group
sync_groups[] = name_of_second_group
...
```

**Comment by wastez** [comment] 2021-10-31 21:28
As far as i can say everything is working.
Using it as live system will show us more.

**Comment by wastez** [comment] 2021-10-31 21:49
Thank you again for your great work and your great support, it's really great.

If you wish a donation for your work just give me a account where it can be transfered.

**Comment by thomas-pike** [comment] 2021-10-31 22:04
You're welcome. It's good to know this tool is still finding use out there.

No payment necessary, but thank you very much for offering.

**Comment by wastez** [comment] 2021-11-02 09:59
Hello,

FIrst issue, i'm not able to add a group to add a ldap group as a server administrator.
The Oops screen appears.

**Comment by wastez** [comment] 2021-11-02 10:06
ErrorException: Undefined index: mail in /srv/keys/model/user.php:316\n1635847436: Stack trace:\n1635847436: #0 /srv/keys/model/user.php(316): exception_error_handler()\n1635847436: #1 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1635847436: #2 /srv/keys/views/server.php(45): UserDirectory->get_user_by_uid()\n1635847436: #3 /srv/keys/requesthandler.php(65): require('/srv/keys/views...')\n1635847436: #4 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1635847436: #5 {main}, referer: https://server-hostname.test.com/servers/client-hostname.test.com

**Comment by wastez** [comment] 2021-11-02 10:13
Looks like you have to edit your code in keys/requesthandler.php for LDAP groups.
LDAP groups don't have a mailaddress. *gggg

**Comment by wastez** [comment] 2021-11-02 10:43
And if user is in the ldap group by first login:
`): User->get_details_from_ldap()\n1635849386: #2 /srv/keys/requesthandler.php(24): UserDirectory->get_user_by_uid()\n1635849386: #3 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1635849386: #4 {main}, referer: https://server.test.com/
[Tue Nov 02 11:36:27.497328 2021] [php7:notice] [pid 235090] [client 172.24.196.64:60666] 1635849387: InvalidArgumentException: Entity must be in directory before it can be added to a group in /srv/keys/model/group.php:118\n1635849387: Stack trace:\n1635849387: #0 /srv/keys/model/user.php(352): Group->add_member()\n1635849387: #1 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1635849387: #2 /srv/keys/requesthandler.php(24): UserDirectory->get_user_by_uid()\n1635849387: #3 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1635849387: #4 {main}, referer: https://server.test.com/
[Tue Nov 02 11:36:29.400812 2021] [php7:notice] [pid 240081] [client 172.24.196.64:60668] 1635849389: InvalidArgumentException: Entity must be in directory before it can be added to a group in /srv/keys/model/group.php:118\n1635849389: Stack trace:\n1635849389: #0 /srv/keys/model/user.php(352): Group->add_member()\n1635849389: #1 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1635849389: #2 /srv/keys/requesthandler.php(24): UserDirectory->get_user_by_uid()\n1635849389: #3 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1635849389: #4 {main}, referer: https://server.test.com/users
[Tue Nov 02 11:36:30.485067 2021] [php7:notice] [pid 237721] [client 172.24.196.64:60670] 1635849390: InvalidArgumentException: Entity must be in directory before it can be added to a group in /srv/keys/model/group.php:118\n1635849390: Stack trace:\n1635849390: #0 /srv/keys/model/user.php(352): Group->add_member()\n1635849390: #1 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1635849390: #2 /srv/keys/requesthandler.php(24): UserDirectory->get_user_by_uid()\n1635849390: #3 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1635849390: #4 {main}, referer: https://server.test.com/groups
[Tue Nov 02 11:37:01.024217 2021] [php7:notice] [pid 235088] [client 172.24.196.64:60684] 1635849421: InvalidArgumentException: Entity must be in directory before it can be added to a group in /srv/keys/model/group.php:118\n1635849421: Stack trace:\n1635849421: #0 /srv/keys/model/user.php(352): Group->add_member()\n1635849421: #1 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1635849421: #2 /srv/keys/requesthandler.php(24): UserDirectory->get_user_by_uid()\n1635849421: #3 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1635849421: #4 {main}, referer: https://server.test.com/pubkeys
[Tue Nov 02 11:37:20.793590 2021] [php7:notice] [pid 237721] [client 172.24.196.64:60698] 1635849440: InvalidArgumentException: Entity must be in directory before it can be added to a group in /srv/keys/model/group.php:118\n1635849440: Stack trace:\n1635849440: #0 /srv/keys/model/user.php(352): Group->add_member()\n1635849440: #1 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1635849440: #2 /srv/keys/requesthandler.php(24): UserDirectory->get_user_by_uid()\n1635849440: #3 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1635849440: #4 {main`

**Comment by wastez** [comment] 2021-11-03 15:16
In both cases i know where the problem is, if the logs are to less.
For the ldap group problem on the the first login i wrote a dirty fix to solve it in the meantime, but as i said i'm not good in php.

**Comment by thomas-pike** [comment] 2021-11-07 11:20
Apologies for the trouble, clearly I needed to do more testing, which I have done now. I've pushed a fix for the LDAP group problem.

As for your other problem, I believe it is unrelated to the group changes, and is caused by a user in your LDAP directory that doesn't have a `mail` attribute (I'm guessing that you have `user_email = mail` in your `[ldap]` config, and this code is currently assuming that *all* users have at minimum the `user_id`, `user_name` and `user_email` attributes. I'm not sure what the preferred behaviour should be for a user that doesn't have all of those...

**Comment by wastez** [comment] 2021-11-07 12:10
Hello,

No thats sureley not the problem, users without mail can't be added via ldap.
A default group is working, (with the same users inside) but not a ldap group.
Could it be that that this if is accepted also on groups, which isn't accepted when using a default group?
`if($ldapuser = reset($ldapusers)) {`

**Comment by wastez** [comment] 2021-11-07 12:22
And your group fix still have a problem if the group is already inside when user is still added:

[Sun Nov 07 13:19:49.046414 2021] [php7:notice] [pid 47254] [client 172.24.196.58:59434] 1636287589: ErrorException: Trying to get property 'uid' of non-object in /srv/keys/model/group.php:123\n1636287589: Stack trace:\n1636287589: #0 /srv/keys/model/group.php(123): exception_error_handler()\n1636287589: #1 /srv/keys/model/user.php(356): Group->add_member()\n1636287589: #2 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1636287589: #3 /srv/keys/requesthandler.php(24): UserDirectory->get_user_by_uid()\n1636287589: #4 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1636287589: #5 {main}, referer: https://testserver.test.com/users/x-test03

**Comment by thomas-pike** [comment] 2021-11-07 12:40
> No thats sureley not the problem, users without mail can't be added via ldap. A default group is working, (with the same users inside) but not a ldap group. Could it be that that this if is accepted also on ldap groups, which isn't accepted when using a default group? `if($ldapuser = reset($ldapusers)) {`
> 
> Edit: I double checked the users in the mysql db, every user have a email.

If this was the error you are getting:

```
ErrorException: Undefined index: mail in /srv/keys/model/user.php:316
```

then I do not see how it can be anything other than a user in LDAP missing a mail attribute. _Especially_ since the previous 2 lines, fetching the user_id and user_name lines for the same user succeeded without error.

**Comment by wastez** [comment] 2021-11-07 12:42
Maybe i've the problem, my config is looking like that:
user_id = sAMAccountName
user_name = cn
user_email = mail

I'm using a samba ad, the users have no uid attribute.

**Comment by thomas-pike** [comment] 2021-11-07 12:43
> And your group fix still have a problem if the user is still added to the group:

Yes, this is still problematic it seems. My testing did not reveal this because my very limited test setup does not have outgoing email enabled. This is going to be tricky to solve properly as there are circular dependencies going on here.

**Comment by wastez** [comment] 2021-11-07 12:45
Wouln't it be better you took the relations from the config.ini?
As wroting in hardcoded.

**Comment by thomas-pike** [comment] 2021-11-07 12:49
> Wouldn't it be better you take the relations from the config.ini? As wroting it hardcoded.

This is getting very confusing having 2 different issues in the same ticket. If you're referring to the LDAP attributes used, those are indeed using the values from config.ini.

Lines 314-316 of `model/user.php` are fetching the attributes from LDAP based on the values of `user_id`, `user_name` and `user_email` specified in your config.ini. You are getting an error on line 316, which means it has already successfully retreived both the `user_id` (in your case `sAMAccountName`) and the `user_name` (in your case `cn`) from LDAP, but you are encountering the error on line 316, which is trying to fetch the `user_email` (in your case `mail`) from LDAP. Since this is the line you are having the error on, I am unable to draw any conclusion other than you have a user in LDAP that is missing its `mail` attribute.

**Comment by wastez** [comment] 2021-11-07 12:52
No, the problem is not the mail, every user has a mail, also in the db.
Also the mail is available in the users attribute on my samba ad.
But the users doesn't have a uid in samba ad.
As i said my php is not good.

**Comment by thomas-pike** [comment] 2021-11-07 12:58
Sorry, but again I repeat: _if_ you are encountering the error on line _316_ of model/user.php and the error is that the `mail` attribute is undefined, then **there is _no other explanation_ than that _a_ user is lacking the `mail` attribute _in LDAP_**. It is literally impossible to be anything else. This is not about what's in the database. This is about what's in LDAP.

**Comment by wastez** [comment] 2021-11-07 12:59
Right now i`m talking about adding groups as admin to servers and this is the error message:

`[Sun Nov 07 13:19:49.046414 2021] [php7:notice] [pid 47254] [client 172.24.196.58:59434] 1636287589: ErrorException: Trying to get property 'uid' of non-object in /srv/keys/model/group.php:123\n1636287589: Stack trace:\n1636287589: #0 /srv/keys/model/group.php(123): exception_error_handler()\n1636287589: #1 /srv/keys/model/user.php(356): Group->add_member()\n1636287589: #2 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1636287589: #3 /srv/keys/requesthandler.php(24): UserDirectory->get_user_by_uid()\n1636287589: #4 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1636287589: #5 {main}, referer: https://x-vie01-keyauth-test01.x/users/x-test03`

**Comment by thomas-pike** [comment] 2021-11-07 13:01
Right, and that is a completely different error to the one I was talking about.

That comment was referring to this error that you mentioned earlier:

```
ErrorException: Undefined index: mail in /srv/keys/model/user.php:316\n1635847436: Stack trace:\n1635847436: #0 /srv/keys/model/user.php(316): exception_error_handler()\n1635847436: #1 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1635847436: #2 /srv/keys/views/server.php(45): UserDirectory->get_user_by_uid()\n1635847436: #3 /srv/keys/requesthandler.php(65): require('/srv/keys/views...')\n1635847436: #4 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1635847436: #5 {main}, referer: https://server-hostname.test.com/servers/client-hostname.test.com
```

**Comment by wastez** [comment] 2021-11-07 13:02
Sorry this message was from the first logon:

`[Sun Nov 07 13:19:49.046414 2021] [php7:notice] [pid 47254] [client 172.24.196.58:59434] 1636287589: ErrorException: Trying to get property 'uid' of non-object in /srv/keys/model/group.php:123\n1636287589: Stack trace:\n1636287589: #0 /srv/keys/model/group.php(123): exception_error_handler()\n1636287589: #1 /srv/keys/model/user.php(356): Group->add_member()\n1636287589: #2 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1636287589: #3 /srv/keys/requesthandler.php(24): UserDirectory->get_user_by_uid()\n1636287589: #4 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1636287589: #5 {main}, referer: https://x-vie01-keyauth-test01.x/users/x-test03`

**Comment by thomas-pike** [comment] 2021-11-07 13:02
Yes, and as I said above:

>> And your group fix still have a problem if the user is still added to the group:

> Yes, this is still problematic it seems. My testing did not reveal this possibly because my very limited test setup does not have outgoing email enabled. This is going to be tricky to solve properly as there are circular dependencies going on here.

**Comment by thomas-pike** [comment] 2021-11-07 13:13
The problem occurs whether or not outgoing emails are enabled. It is triggered as you say by first login. I had added the user to the database in a different way (by granting them access to a server account), thus triggering a somewhat different code path.

**Comment by wastez** [comment] 2021-11-07 13:14
Granting them to a server account is working without problems.

**Comment by wastez** [comment] 2021-11-07 13:17
But as soon i add an admin to an server i get this:
`[Sun Nov 07 14:15:43.534998 2021] [php7:notice] [pid 51043] [client x.x.x.x:60947] 1636290943: ErrorException: Undefined index: mail in /srv/keys/model/user.php:316\n1636290943: Stack trace:\n1636290943: #0 /srv/keys/model/user.php(316): exception_error_handler()\n1636290943: #1 /srv/keys/model/userdirectory.php(99): User->get_details_from_ldap()\n1636290943: #2 /srv/keys/views/server.php(45): UserDirectory->get_user_by_uid()\n1636290943: #3 /srv/keys/requesthandler.php(65): require('/srv/keys/views...')\n1636290943: #4 /srv/keys/public_html/init.php(18): require('/srv/keys/reque...')\n1636290943: #5 {main}, referer: https://testserver.test.com/servers/x-l-samba03.l.x`

But the clue is every user have in ldap a mail attribute.

**Comment by thomas-pike** [comment] 2021-11-07 13:21
These are 2 very separate issues, and as I said, it is **very** confusing having both issues in the same ticket. And again, I refer you to this comment: https://github.com/operasoftware/ssh-key-authority/issues/55#issuecomment-962606227

**Comment by wastez** [comment] 2021-11-07 13:24
I know what you wrote, and in LDAP every users which is in the group has the mail attribute and it is filled with the correct mail address.

**Comment by thomas-pike** [comment] 2021-11-07 13:25
Then we are at an impasse with that issue, because there is no other explanation.

**Comment by wastez** [comment] 2021-11-07 13:29
I now know what the problem is.
The group have a empty mail attribute field.
I entered a group to test and now it was working.

**Comment by thomas-pike** [comment] 2021-11-07 13:30
That would indicate that a group is being treated as a user. That is concerning.

**Comment by wastez** [comment] 2021-11-07 13:31
Exactly, so your `if($ldapuser = reset($ldapusers)) {` seems to also be entered on groups.

**Comment by thomas-pike** [comment] 2021-11-07 13:32
It should not be getting even that far. It would mean that `get_details_from_ldap()` is being called for a group, and that should not be the case.

**Comment by wastez** [comment] 2021-11-07 13:33
Before you didn't had this problem, because you are not using ldap groups.

**Comment by thomas-pike** [comment] 2021-11-07 13:41
As far as I can tell it shouldn't matter. If the entity is an object of type `Group`, it should not have a `->get_details_from_ldap()` method to call. Of course there is the slim possibility that something is *extremely* broken in the code here that means a group is being treated as a user, but I don't _think_ that can be the case.

Do you have any record in the `user` table in the database whose name matches the name of a group in LDAP?

**Comment by thomas-pike** [comment] 2021-11-07 13:45
And a follow-up question: are your groups in LDAP in separate subtrees from your users? ie. are your `dn_user` and `dn_group` config settings distinctly separate?

**Comment by wastez** [comment] 2021-11-07 13:45
No of course no record in user table matches the group name in ldap.

We have naming conventions on our ldap, so thats impossible.
But i also dopple checked it right now.

**Comment by wastez** [comment] 2021-11-07 13:46
No its the same subtree.

**Comment by wastez** [comment] 2021-11-07 13:47
So you just difference it by subtree? That would clearly show the problem.

**Comment by thomas-pike** [comment] 2021-11-07 13:53
Typically groups would be in a separate subtree from users, eg. as in the example config:
```
; LDAP subtree containing USER entries
dn_user = "ou=users,dc=example,dc=com"
; LDAP subtree containing GROUP entries
dn_group = "ou=groups,dc=example,dc=com"
```
If they are in the same subtree then it could potentially cause problems _if_ there were a naming conflict. But you say that you have separate conventions for groups, so I'm not sure that's possible.

It seems to be that it is trying to add a new user to the database, and for some reason it has fetched the details of a group from LDAP. I can't really explain that at the moment.

**Comment by thomas-pike** [comment] 2021-11-07 14:00
Your stacktrace is showing the following path through the code:
* `/srv/keys/views/server.php(45)`: `$entity = $user_dir->get_user_by_uid($_POST['user_name']);`
* `/srv/keys/model/userdirectory.php(99)`: `$user->get_details_from_ldap();`
* `/srv/keys/model/user.php(316)`: <- Error encountered here

It hasn't reached any group-related code at this point. It is trying to fetch details of the user specified in the form, a user that is not yet in the database.

**Comment by wastez** [comment] 2021-11-07 14:03
Yes, right now, the group and users are in the same subtree.
But as i said naming conventions doesn't allow to have the same name in groups and in users.

**Comment by wastez** [comment] 2021-11-07 14:06
And yes the group was now added as user.

**Comment by thomas-pike** [comment] 2021-11-07 14:10
Ok, so we've got to the bottom of this. You are trying to add a group as an administrator of a server. Line 45 of `views/server.php` tries first to find a user with the name given. It searches the user subtree and finds a record that matches, assumes it to be a user and tries to treat it as such. Normally it would not find any such entry, and would proceed to line 48  of `views/server.php` where it tries to find a group with the name, but since you have both users and groups in the same subtree it finds a group at the point where it's expecting a user.

This problem is therefore unrelated to the changes made in this ticket to support fetching LDAP groups for users. I'm not sure there's any good solution for it either.

**Comment by thomas-pike** [comment] 2021-11-07 14:12
The only proper fix for that issue I can think of is having 2 separate fields in the UI, one for adding a user as an admin, and one for adding a group. Even so, it would still encounter errors if you accidentally used the wrong field.

**Comment by wastez** [comment] 2021-11-07 14:13
And you can't add a filter for users and for groups in the ldap search?

**Comment by thomas-pike** [comment] 2021-11-07 14:15
Possibly. That would require adding more settings to the config file for user_query and group_query. I'll make a separate ticket for that.

**Comment by thomas-pike** [comment] 2021-11-07 14:18
Filed #60 for the user/group mismatch issue.

**Comment by wastez** [comment] 2021-11-07 14:45
Just for your information:
I tried to use different subtrees on our testsystem.
With our old database the sync throws a error:
```
PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect integer value: '' for column 'admin' at row 1 in /srv/keys/model/record.php:155
Stack trace:
#0 /srv/keys/model/record.php(155): mysqli_stmt->execute()
#1 /srv/keys/model/user.php(46): Record->update()
#2 /srv/keys/model/user.php(335): User->update()
#3 /srv/keys/scripts/ldap_update.php(42): User->get_details_from_ldap()
#4 {main}
  thrown in /srv/keys/model/record.php on line 155
```

In a new Database the was no problem.
But switching the group folder with the existing database results in an error.
But if you add a filter now this problem should be obsolete.

**Comment by thomas-pike** [comment] 2021-11-07 15:06
#60 has been resolved, you can now add `user_filter` and `group_filter` in your config.ini. See config-sample.ini for suggested values.

I also noticed the `Incorrect integer value: '' for column 'admin'` error and added a fix for that.

**Comment by thomas-pike** [comment] 2021-11-07 15:09
That should just leave one remaining bug: first login group membership triggering an error due to `$active_user` not being set.

**Comment by wastez** [comment] 2021-11-07 19:31
Any chance to get this solved? Or is this a bigger change?

**Comment by thomas-pike** [comment] 2021-11-07 20:09
There's a tentative fix for this on the `set_active_user` branch. Please feel free to try it out.

**Comment by wastez** [comment] 2021-11-07 20:14
Login is working as it should now.
Any suggestions what to test?
Do you know what could be affected?

**Comment by wastez** [comment] 2021-11-07 20:20
I tested a lot right now.
It really looks good.

**Comment by thomas-pike** [comment] 2021-11-07 20:36
As long as it is working for you, this should be a reasonably low-risk change. I'll merge it now.

**Comment by wastez** [comment] 2021-11-07 20:37
Ok fine.
Everthing is working and i tried a lot things, so everything should be ok.

**Closed** 2021-11-07 20:36 UTC
Labels: enhancement
